export enum CodemirrorTheme {
    /*
C:\projets\creative\ohimark\node_modules\codemirror\theme\zenburn.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\3024-day.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\3024-night.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\abcdef.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\ambiance-mobile.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\ambiance.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\base16-dark.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\base16-light.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\bespin.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\blackboard.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\cobalt.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\colorforth.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\dracula.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\duotone-dark.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\duotone-light.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\eclipse.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\elegant.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\erlang-dark.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\hopscotch.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\icecoder.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\isotope.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\lesser-dark.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\liquibyte.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\material.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\mbo.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\mdn-like.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\midnight.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\monokai.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\neat.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\neo.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\night.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\oceanic-next.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\panda-syntax.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\paraiso-dark.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\paraiso-light.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\pastel-on-dark.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\railscasts.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\rubyblue.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\seti.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\shadowfox.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\solarized.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\the-matrix.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\tomorrow-night-bright.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\tomorrow-night-eighties.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\ttcn.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\twilight.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\vibrant-ink.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\xq-dark.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\xq-light.css
C:\projets\creative\ohimark\node_modules\codemirror\theme\yeti.css
*/
}
